### ISSUE TITLE
Make currency symbols

### ISSUE THREAD

**Issue by phildini** [ImmaculateObsession/xenotime#10]
So tiles are going to cost forest and city points. We need cool little currency tiles that represent forest and city currency.

**Comment by phildini** [comment]
These are cool. I like em. Feel free to be more abstract with the forest coins. What represents currency in the forest?

**Comment by elzilrac** [comment]
To be perfectly honest I hadn't fully read the issue and hadn't thought of
a forest coin! Will keep working on it.
