### ISSUE TITLE
HUD Concept

### ISSUE THREAD

**Issue by phildini** [ImmaculateObsession/xenotime#21]
Create concept art for the HUD. 

Should include:
- Spaces for each tile type
- Spaces for inventory
- Notification center space
- Space for the game grid, which is currently 640x640.

**Comment by phildini** [comment]
New idea: Desktop with book containing play grid.

**Comment by elzilrac** [comment]
WIP for hud,
![hud_ideas2](https://f.cloud.github.com/assets/1740393/101541/b8a052b4-68d5-11e2-89ac-00743c1e307d.png)

**Comment by phildini** [comment]
I LIKE IT! I think this is a really good direction to go with.

I'm excited to see what the next version looks like, and I'll start putting the rough structure in place in the code.

**Comment by phildini** [comment]
I'm going to mark this closed, since it satisfies having the concept done. I'll create a new task for having the actual asset.
