### ISSUE TITLE
Loading Screen Asset v1

### ISSUE THREAD

**Issue by phildini** [ImmaculateObsession/xenotime#26]
This should (currently) be a flat image that is the size of the game screen (currently 1024x768).

Top left corner should have some cool vine/plant design. 
Bottom right corner can be a city scape or stylized bridge.
Text in the center should say "Searching..."

**Comment by elzilrac** [comment]
WIP- would like input at today's meeting.

![hud_ideas](https://f.cloud.github.com/assets/1740393/101327/313fbc1a-68bc-11e2-8a3f-38a67252efc8.png)

**Comment by phildini** [comment]
Did you mean to post this on #21?
