### ISSUE TITLE
Load from/ Save To a specific file format

### ISSUE THREAD

**Issue by phildini** [ImmaculateObsession/xenotime#29]
This builds off the earlier work dome by @vewong for saving and loading.

We want to be able to write and read level files in a meaningful format (read: plain text). 

That format should follow the format laid out in Level.as currently where each tile on the grid is represented by an integer that corresponds to the spritesheet position. 

There should be two types of level files: Layout files and player save files.

Initial level files should look like this:

Level: 1
0,0,7,0,0,0,0,13,0,0,
0,0,8,0,0,0,0,14,0,0,
0,0,0,11,12,0,0,0,0,0,
0,0,0,0,0,0,0,7,0,0,
7,0,0,0,0,0,0,8,0,0,
8,0,0,13,0,0,0,0,0,0,
0,0,0,14,0,9,10,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,13,0,0,0,0,0,11,12,0,
0,14,0,0,0,0,0,0,0,0

Save/solution files should look like this (assuming the player has placed no tiles):

Level:1
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0

If there are any questions, let me know.

**Comment by vewong** [comment]
There's a problem with writing to a file when saving/loading from a browser (which I assume is the main target platform of this game) because, in my research, you're not allowed access to files from running in a browser, which is one of the reasons I chose to use Flixel's save state. If you want, I can try and look into saving and loading from files through the browser again, though.

**Comment by phildini** [comment]
Hmm. This is a bigger project than I realized, and also a perfect topic of
discussion for a 1on1. ;) Let's take this offline and set up a time.

Philip James
http://philipjohnjames.com

**Comment by elzilrac** [comment]
I have experience beating my head into the wall about exporting files. 
Long story short, I suggest long-lasting cookies if you must use the non 
flixel save state. It is an extreme pain even if the html page you are 
running and trying to save with is locally stored on your machine.

**Comment by phildini** [comment]
Let's de-prioritize this for now. At some point, it would be awesome to have these files saved to a server, either using the Url or externalInterface methods in as3, but just knowing that we can save is satisfactory. Thanks!
