### ISSUE TITLE
Optimize art/asset folders

### ISSUE THREAD

**Issue by phildini** [ImmaculateObsession/xenotime#7]
### Overview
- the art folder should be a working folder for the artists
- the assets folder should have just what is being used in the game. right now, that is tilemap.png (and maybe a text file of the positions of things on the tile map)
- the art folder should have a raw folder ( for psds, sais, etc) and a finished folder (for pieces ready to go into the tilemap)

**Comment by phildini** [comment]
I took a look at the rotation buttons, great work.

Instead of having them be a complete circle, could you change it to a 1/2 or 3/4 circle? I think that will help emphasize the purpose of the button.

Also, it looks like you were trying to make the counter-clockwise button more foresty, and the clockwise button more city. That is an awesome dedication to our theme, but makes the foresty button look a little... muddy? rough? I think its going to be helpful to have the rotation buttons be consistent. Could they both be done in the style of the city one? 

Thanks for being flexible!

P.S: As a workflow suggestion, I would say not to delete any assets you've created and exported, even if the requirements change. The .psds and .sais are your domain, you can either edit them or create new ones, but the .pngs I would just leave and export new ones. You never know when, in the future, we'll need a thing that you created earlier. :)

**Comment by elzilrac** [comment]
I will be moving unused stuff to the "concept" folder. I still have to sort through some of my local stuff and add it. But it's 1am and I'm sleepy ;)

Also duplicated and rotated the 3/4 city rotate button. Changes are in the tilemap in the finished folder (art/finished). I don't think I can make changes to the actual assets folder? BUT I did switch the ordering of some tiles to be more consistent (see forest pipes).
